[package]
name = "signal-take-home"
version = "0.1.0"
authors = ["Daniel Porteous <danielporteous1@gmail.com>"]
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"

